household_power_consumption <- read.csv("C:/Users/Punz/Desktop/Corsera/household_power_consumption.txt", sep=";")
hpc = household_power_consumption
subhpc = subset(hpc,hpc$Date=="1/2/2007" | hpc$Date =="2/2/2007")
subhpc$Date = as.Date(subhpc$Date, format="%d/%m/%Y")
subhpc$Time = strptime(subhpc$Time, format="%H/%M/%S")
subhpc[1:1440,"Time"] = format(subhpc[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subhpc[1441:2880,"Time"] = format(subhpc[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
par(mfrow=c(2,2))
with(subhpc,{
    plot(subhpc$Time,as.numeric(as.character(subhpc$Global_active_power)),type="l",  xlab="",ylab="Global Active Power")  
    plot(subhpc$Time,as.numeric(as.character(subhpc$Voltage)), type="l",xlab="datetime",ylab="Voltage")
    plot(subhpc$Time,subhpc$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
    with(subhpc,lines(Time,as.numeric(as.character(Sub_metering_1))))
    with(subhpc,lines(Time,as.numeric(as.character(Sub_metering_2)),col="red"))
    with(subhpc,lines(Time,as.numeric(as.character(Sub_metering_3)),col="blue"))
    legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex = 0.6)
    plot(subhpc$Time,as.numeric(as.character(subhpc$Global_reactive_power)),type="l",xlab="datetime",ylab="Global_reactive_power")
 })